version: "3.9"

volumes:
  postgres-data:

services:
  postgres:
    container_name: postgres_bot
    image: postgres:15
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 15s
    networks:
      - repeater_bot_network

  s3:
    container_name: minio_bot
    image: minio/minio:RELEASE.2024-01-18T22-51-28Z
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file: .env
    command: server /data --console-address ":9001"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://s3:9000/minio/health/live || exit 1" ]
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 15s
    networks:
      - repeater_bot_network

networks:
  repeater_bot_network:
